### ISSUE TITLE
README.md里面的命令貌似写错了

### ISSUE THREAD

**Issue by Koukotsukan** [wuhan-support/robot-personal#3]
docker logs ncovwerobot_ncov_robot_1报错no such container
改成docker logs robot-personal_ncov_robot_1后解决
但是好像是我的docker内存不够 输入命令以后返回了好几个Killed，另外谢谢作者的贡献

**Comment by Maicius** [comment]
感谢指出，可能是操作系统或docker版本的问题，在以后的版本中会放弃使用docker，直接打包为exe或可执行文件

**Comment by Koukotsukan** [comment]
感谢！
